### ISSUE TITLE
[5.0 Beta 4] List of noticed issues to take in care

### ISSUE THREAD

**Issue by Valc** [infograf768/j4localise#21]
Noticed after 5.0 Beta 4 installation

- Help system does not work (no "help" folder present when com_localise is installed), seems better get a white content result than a 404 not found
- The list of non-core files at "packagefile"  view now is adding core language files to select. Seems is issued by extra "ini.ini" due "`self::suffix_array_values`" call. Simply commenting that 2 lines  should solve the issue. **Solved** https://github.com/infograf768/j4localise/commit/164941a6d54bd6743777588fe8d6341123aa608c
- The "Reset all" button at translation view is not working and  seems is no mater if actual JS is "wrapped" or not, i think than by normal jQuery should be solved easy. i am not able to understand the odd code used now that is using $$, but i can solve using other. **Solved** https://github.com/infograf768/j4localise/commit/aa98e46a32128b1d56d03b28c5421ac9573bac62
- The core package view allow select "com_loalise" as extra file but it never can create a package due is not at core folders location. Seems logic try to solve avoiding show files not present at core folders when we are handling core packs.

ADDED

- Com_localise keep old format 'xx-XX'  for him translations language file names https://github.com/infograf768/j4localise/pull/24#issuecomment-913120064
- The XML output when download, export or import need to be revised to match the actual standar format  with `<files></files>` https://github.com/infograf768/j4localise/pull/23#issuecomment-913121830

**Comment by Valc** [comment]
@infograf768 
PR to "Reset all" is here:
https://github.com/infograf768/j4localise/pull/22

**Comment by Valc** [comment]
@infograf768
PR to "Core at non core" is here:
https://github.com/infograf768/j4localise/pull/23

**Comment by Valc** [comment]
@infograf768

I have also noticed that maybe some PRs are not applied at "master" branch. For example:

https://github.com/infograf768/j4localise/blob/master/administrator/components/com_localise/tmpl/translation/edit.php

Have not applied the PR at master brach

**Comment by infograf768** [comment]
It is applied in fact ;)

see https://github.com/infograf768/j4localise/blob/master/administrator/components/com_localise/tmpl/translation/edit.php#L96-L105

**Comment by Valc** [comment]
uf, uf.. thanks for clarifying

**Comment by infograf768** [comment]
@Valc 
We can decide: do we create a help system or just take it off from the managers.
What do you think?

Also, I have a PR to reformat the 3rd party extensions with language folder. Please test
https://github.com/infograf768/j4localise/pull/25

**Comment by Valc** [comment]
@infograf768 

> We can decide: do we create a help system or just take it off from the managers.
> What do you think?

I think is good idea keep a help site working. Note that we have no "Wiki" here and some locations maybe are not easy to config from new users or TTs.

For now, I would just add the "help" folder and we will avoid getting 404 errors.
Also, instead of loading a blank page, we could put some HTML code like "Under construction see your questions in wherever we can help"

If you create a rough draft of how you want to make the help system, I could help out with that reference.

Now i am working solving this one:

`The core package view allow select "com_loalise" as extra file but it never can create a package due is not at core folders location. Seems logic try to solve avoiding show files not present at core folders when we are handling core packs.`

Really easy to solve from the core package case, but at same time i am taking a look about how to minimize the "scans" calls from there with the only required tags to use it from the TranslationsField, than for me is only required the referencce one, but i also trying to get ALWAYS the "language" value and seems is bit resistant but i will do.. XD

I will test your patch in a bit :)

**Comment by infograf768** [comment]
Re: help system
I have no time nor the will to work on help screens.
I doubt anyone will volunteer as it has to be done with good en-GB and captures.

If you feel you can do, please make a PR. For me, taking off the Help button is much easier.
reminder: in 3.x we get a blank popup, which is not satisfying at all. ;)

**Comment by Valc** [comment]
@infograf768 
> taking off the Help button is much easier.
Please, do it.

The only thing I can help with now is by opening a Github wiki on my clone, with some informal content and trying to explain some key setup and usage points, with my poor English and some images not optimized for the web :D

And, of course, from the aply at your wiki what you wanna use and improve from there,

**Comment by Valc** [comment]
`The core package view allow select "com_loalise" as extra file but it never can create a package due is not at core folders location. Seems logic try to solve avoiding show files not present at core folders when we are handling core packs.`
PR here:
https://github.com/infograf768/j4localise/pull/26

**Comment by infograf768** [comment]
> And, of course, from there apply at your wiki what you wanna use and improve from there,

I have no wiki and no intention to create one. 😄 
OK, will take off the Help button and test PR #26

**Comment by Valc** [comment]
> I have no wiki and no intention to create one.

@infograf768 
You make me laught!! jajajjajajaa

I am in line with you, due i had no intention too: i will leave it to the last one to do, but i will try it XD

I have founded another issue, i think it is comming from my beta 2 test, that i am not able to reproduce again or solve, but is there.

I remember than i try to solve deleting packages, purge, logout, reinstall the extension and one of the was the solution without touch code lines.

Due i like `die(var_dump($aaaall));`  and also  "grep", here the "grep" output than matches with it:
```
`JViewGenericdataexception` was called and i does not know why, but seems it is now obsolete.

../com_localise-5.0.0-beta3/component/admin/View/Packages/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Packagefiles/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Language/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Languages/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Translation/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Translations/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
../component/admin/View/Package/HtmlView.php:			throw new \JViewGenericdataexception(implode("\n", $errors), 500);
```
I have founded this one and you are at participants list. So, maybe you know how to solve this one.
I was trying to apply the solution "adding use" and reanaming it but no luck.

**Comment by infograf768** [comment]
`\JViewGenericdataexception` is indeed obsolete. I guess the solution is the same as in https://issues.joomla.org/tracker/joomla-cms/24718

What do you mean by `but no luck` ?

Normally, we should add in 8 com_localise files
`use Joomla\CMS\MVC\View\GenericDataException;`

and then modify the line in each of the 8 views
from
`throw new \JViewGenericdataexception(implode("\n", $errors), 500);`
to
`throw new GenericDataException(implode("\n", $errors), 500);`

as everywhere in core.

**Comment by Valc** [comment]
> use Joomla\CMS\MVC\View\GenericDataException;

Mmmm, i think it was due my test to solve was using Generic**d**ataException and not Generic**D**ataException

**Comment by infograf768** [comment]
OK, will correct these 8 files and merge directly.

**Comment by infograf768** [comment]
https://github.com/infograf768/j4localise/commit/580d4950631680a95951c84edaaac21ceff09a87

**Comment by Valc** [comment]
:+1:

**Comment by infograf768** [comment]
@valc
I commented the help buttons
https://github.com/infograf768/j4localise/commit/9e0e3011903c5c499b6e7e8a20dbe26899f473a3

Therefore I am closing this and I think we should now open an issue per item.

**Comment by Valc** [comment]
> @Valc
> I commented the help buttons
> [9e0e301](https://github.com/infograf768/j4localise/commit/9e0e3011903c5c499b6e7e8a20dbe26899f473a3)
> 
> Therefore I am closing this and I think we should now open an issue per item.

:+1:
