### ISSUE TITLE
Not in reference items deletion

### ISSUE THREAD

**Issue by infograf768** [infograf768/j4localise#30]
@Valc 
Would be great to create the ability to delete a string which is in the `Not in reference` section directly from the basic view and not have to switch to the `raw` view to do that.

Example: this string has been deleted recently in 4.0-dev.
<img width="816" alt="Screen Shot 2021-09-22 at 11 49 50" src="https://user-images.githubusercontent.com/869724/134322553-e9440c40-e3bc-4f39-a4b9-6fbdc2625bb4.png">

If we can, then we need modify the info on top of the page.

**Comment by Valc** [comment]
It seems good idea.
I think i can handle it.

Some questions before start:

Translators than handle plural cases i imagine than that ones are added as "not in reference" or "extra in translation" too.

This one can be handled if always follow a pathern. Example: key ends always with "_1", "_2" (no idea, i never have required use that one at es-ES, i simply know than some languages are adding plural cases, following a patern).

1. You than know in deep  that matter, if it is added as "not in reference", can you share a list of the "end of keys pattern" to skip if required due plural cases?
2. "Captcha keys" or "Forum ids keys" are still used at J4? or more "especial cases" you know to take in mind?

This will ensure we only delete extra keys in translations and extra plural extra keys in translations due the key in not present in reference yet, but not the extra keys in translation due required plural cases.


Other stuff is that save or apply at translation edit view is already using an alert message and i does not know if by Joomla API we can call "alert messages" type "Yes, No, Cancel" due if not the case i will directly start using a "modal" window than can allow solve the "check as complete" case and "delete extra keys in translation" case at time and seems the "easy to solve" solution.

**Comment by infograf768** [comment]
You are enlarging the issue, but indeed we have a problem with plurals, specially for languages not using the same plurals than en-GB. This is now the case for translations done in crowdin as the plurals have been modified to the new ones without changing en-GB.
So we have in French:
```
public static function getPluralSuffixes($count)
	{
		if ($count == 0)
		{
			return array('0');
		}
		elseif ($count == 1)
		{
			return array('ONE', '1');
		}
		else
		{
			return array('OTHER', 'MORE');
		}
	}
```
and Crowdin forces use of ONE and OTHER instead of 1 and MORE as before.

I don't think we can fully solve this in com_localise if the pack first came from crowdin.
Example
<img width="777" alt="Screen Shot 2021-09-23 at 09 22 47" src="https://user-images.githubusercontent.com/869724/134468771-621fa1b7-fa10-498d-b926-9f5e6aebe438.png">

![Screen Shot 2021-09-23 at 09 23 36](https://user-images.githubusercontent.com/869724/134468846-be42eacd-170e-4ef3-abb7-7c2d2e571887.png)

As you can see, saving that file in com_localise would include the en-GB translation AND the crowdin translated plural strings, these overridding the en-GB ones.

```
[Not in reference]

COM_CONTENT_N_ITEMS_ARCHIVED_ONE="Article archivé."
COM_CONTENT_N_ITEMS_ARCHIVED_OTHER="%d articles archivés."
COM_CONTENT_N_ITEMS_CHECKED_IN_ONE="Article déverrouillé."
COM_CONTENT_N_ITEMS_CHECKED_IN_OTHER="%d articles déverrouillés."
COM_CONTENT_N_ITEMS_DELETED_ONE="Article supprimé."
COM_CONTENT_N_ITEMS_DELETED_OTHER="%d articles supprimés."
COM_CONTENT_N_ITEMS_FEATURED_ONE="Article épinglé."
COM_CONTENT_N_ITEMS_FEATURED_OTHER="%d articles épinglés."
COM_CONTENT_N_ITEMS_PUBLISHED_ONE="Article publié."
COM_CONTENT_N_ITEMS_PUBLISHED_OTHER="%d articles publiés."
COM_CONTENT_N_ITEMS_TRASHED_ONE="Article mis à la corbeille."
COM_CONTENT_N_ITEMS_TRASHED_OTHER="%d articles mis à la corbeille."
COM_CONTENT_N_ITEMS_UNFEATURED_ONE="Article désépinglé."
COM_CONTENT_N_ITEMS_UNFEATURED_OTHER="%d articles désépinglés."
COM_CONTENT_N_ITEMS_UNPUBLISHED_ONE="Article dépublié."
COM_CONTENT_N_ITEMS_UNPUBLISHED_OTHER="%d articles dépubliés."
COM_CONTENT_N_QUICKICON_ONE="Article"
COM_CONTENT_N_QUICKICON_OTHER="Articles"
COM_CONTENT_N_QUICKICON_SRONLY_ONE="Articles : un article est disponible."
COM_CONTENT_N_QUICKICON_SRONLY_OTHER="Articles : %d articles sont disponibles."
```

![Screen Shot 2021-09-23 at 09 29 03](https://user-images.githubusercontent.com/869724/134469453-474e5f8b-80f6-4097-8002-96e94ba9e970.png)

Therefore, it would work in this case by adding 20 strings (for that file).
But some languages use much more complex plurals.

Welsh for example uses
```
public static function getPluralSuffixes($count)
	{
		if ($count == 0)
		{
			return array('ZERO', '0');
		}
		elseif ($count == 1)
		{
			return array('ONE', '1');
		}
		elseif  ($count == 2)
		{
			return array('TWO', '2');
		}
		elseif ($count == 3)
		{
			return array('FEW', '3');
		}
		elseif ($count == 6)
		{
			return array('MANY', '6');
		}
		else
		{
			return array('OTHER', 'MORE');
		}
	}
 ```
 It works also fine when saved in com_localise, BUT it adds 59 strings in Not in Reference...
 
 Therefore, we should never delete all strings in Not in reference, but select string per string.
 Maybe with a select box (similar to the box used for Modified Value tagging the strings to be deleted on Apply and Save?

**Comment by infograf768** [comment]
Also, you have fake plurals like:
```
COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Please select one version."
COM_CONTENTHISTORY_BUTTON_SELECT_TWO="Please select two versions."
```
Just saw French TT and Welsh did not understand that...
Welsh
```
COM_CONTENTHISTORY_BUTTON_SELECT_ZERO="Dewiswch un fersiwn os gwelwch yn dda."
COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Dewiswch un fersiwn os gwelwch yn dda."
COM_CONTENTHISTORY_BUTTON_SELECT_TWO="Dewiswch ddwy fersiwn os gwelwch yn dda."
COM_CONTENTHISTORY_BUTTON_SELECT_FEW="Dewiswch ddwy fersiwn os gwelwch yn dda."
COM_CONTENTHISTORY_BUTTON_SELECT_MANY="Dewiswch ddwy fersiwn os gwelwch yn dda."
COM_CONTENTHISTORY_BUTTON_SELECT_OTHER="Dewiswch ddwy fersiwn os gwelwch yn dda."
```
and French
```
COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Veuillez sélectionner une version"
COM_CONTENTHISTORY_BUTTON_SELECT_OTHER="Veuillez sélectionner deux versions."
```

Crowdin...

**Comment by Valc** [comment]
@infograf768
Ok, that was the cool and precise info i was needing.

```
Therefore, we should never delete all strings in Not in reference, but select string per string.
Maybe with a select box (similar to the box used for Modified Value tagging the strings to be deleted on Apply and Save?
```
I think is not required select keys one by one. This one is a bit the same than with the "extra suffixes" at file names: with the patter to catch, no one file be skiped XD

The only important to keep in mind if what amount of the plural cases is able to understand Joomla as plural cases and handle them, no matter if they come from Crowdin or from other sources.

You know how to "reformat file names", and "reformat  plural" cases to adjust Crowdin format to com_localise  is not a ploblem, it simply know what format we wanna keep and apply the conversion format we need.

I means that if we need replace "_ONE" by "_1" or viceversa is not a ploblem, that can to be handled. The stuff is to be sure than the Joomla API will be understand the plural case.

The good news is that the code structure handling "notincore" keys is already done and i remember that code from years ago :)

Now first we try to "delete only real extra cases in translation keeping required plurals" (not ajax required i think)

And from other PR and using ajax i think also is posible "Add plurals from selected keys (right click over the  key?) at translation edition view", if for you is ok.

I will send a PR when ready and from there apply next suggestions ;)

**Comment by Valc** [comment]
PR here
https://github.com/infograf768/j4localise/pull/32

**Comment by richard67** [comment]
> Also, you have fake plurals like:
> 
> ```
> COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Please select one version."
> COM_CONTENTHISTORY_BUTTON_SELECT_TWO="Please select two versions."
> ```
> 
> Just saw French TT and Welsh did not understand that...
> Welsh
> 
> ```
> COM_CONTENTHISTORY_BUTTON_SELECT_ZERO="Dewiswch un fersiwn os gwelwch yn dda."
> COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Dewiswch un fersiwn os gwelwch yn dda."
> COM_CONTENTHISTORY_BUTTON_SELECT_TWO="Dewiswch ddwy fersiwn os gwelwch yn dda."
> COM_CONTENTHISTORY_BUTTON_SELECT_FEW="Dewiswch ddwy fersiwn os gwelwch yn dda."
> COM_CONTENTHISTORY_BUTTON_SELECT_MANY="Dewiswch ddwy fersiwn os gwelwch yn dda."
> COM_CONTENTHISTORY_BUTTON_SELECT_OTHER="Dewiswch ddwy fersiwn os gwelwch yn dda."
> ```
> 
> and French
> 
> ```
> COM_CONTENTHISTORY_BUTTON_SELECT_ONE="Veuillez sélectionner une version"
> COM_CONTENTHISTORY_BUTTON_SELECT_OTHER="Veuillez sélectionner deux versions."
> ```
> 
> And also Hungarian.
> 
> Crowdin...

Would the string "MOD_TAGS_SIMILAR_FIELD_ONE" from file "modules/mod_tags_similar/mod_tags_similar.xml" make the same problem?

**Comment by infograf768** [comment]
> Would the string "MOD_TAGS_SIMILAR_FIELD_ONE" from file "modules/mod_tags_similar/mod_tags_similar.xml" make the same problem?

No idea, but it would be safe to modify it. I suggested `MOD_TAGS_SIMILAR_FIELD_ONE_TAG="Any"` in your PR

**Comment by infograf768** [comment]
I guess we can close this now.
