### ISSUE TITLE
Translation view: Save and keep current tab

### ISSUE THREAD

**Issue by infograf768** [infograf768/j4localise#38]
This has been bothering me for ages.
When we display the Strings tab and Save, we are redirected to the Details tab.

I wish we could be redirected to the Strings tab while keeping the specific joomla `uiTab` code.

@Valc Any idea?

**Comment by Valc** [comment]
> This has been bothering me for ages. When we display the Strings tab and Save, we are redirected to the Details tab.
> 
> I wish we could be redirected to the Strings tab while keeping the specific joomla `uiTab` code.
> 
> @Valc Any idea?

@infograf768
if after years... you have some seconds.... (sorry, kidding due you make me laught :D)

At edit view search this code lineas and replace the matches of $tabchoised   = 'default'; to $tabchoised   = 'strings';


```
if (isset($posted['select']['keystatus'])
	&& !empty($posted['select']['keystatus'])
	&& $posted['select']['keystatus'] != 'allkeys'
	)
{
	$filter       = $posted['select']['keystatus'];
	$keystofilter = array ($this->item->$filter);
	$tabchoised   = 'strings';
}
elseif (empty($posted['select']['keystatus']))
{
	$filter       = 'allkeys';
	$keystofilter = array();
	$tabchoised   = 'strings';
}
else
{
	$filter       = 'allkeys';
	$keystofilter = array();
	$tabchoised   = 'strings';
}
```

This one will fix to "strings" tab

**Comment by infograf768** [comment]
Will look at your #40 PR, but I had already played with `$tabchoised` (weird variable name... ;) btw and that was not the solution as it was always redirecting to `strings` even when first edit.

**Comment by Valc** [comment]
@infograf768
I think is solved there. simply needs be configured the default one.
You have write access to my clone. So, please, feel you free to moddify the required one. (tabchoised name is realy weird XD) or set the default one, etc)
Now i was trying to start the "create core installation packages", than should follow OP rules about strict xml format and ini headers (than can to make easy get the PR under control)
It seems is ok for you?

**Comment by infograf768** [comment]
Closing as we have a PR
