### ISSUE TITLE
Localise don't recognize files like "astroid.ini"

### ISSUE THREAD

**Issue by fontanil** [infograf768/j4localise#48]
Hi,

I'm trying to translate Astroid Framework. The english files are en-GB.astroid.ini and en-GB.astroid.sys.ini in administrator/language/en-GB folder.
Localise renamed them into astroid.ini and astroid.sys.ini but they aren't displayed in the listing of files, so I can't translate it.
I renamed it "lib_astroid.ini" and can now see it in Localise.

**Comment by fontanil** [comment]
Sorry, it's in site language folder

**Comment by infograf768** [comment]
Shall this be closed. If yes, please do.
I am going to release com_localise RC1 today

**Comment by infograf768** [comment]
@fontanil
new release
https://github.com/infograf768/j4localise/releases/tag/5.0.0-RC1

**Comment by fontanil** [comment]
This RC1 version does not solve the problem

**Comment by infograf768** [comment]
Where can I download Astroid Framework ?

**Comment by infograf768** [comment]
OK, I found it.

This is totally normal and an error by the coder. astroid is a library and as such the file should be named `lib_astroid.ini` as no language file (except joomla.ini) should be proposed without a prefix like com, mod, plg, lib, tpl.

**Comment by fontanil** [comment]
OK
I said this sometimes ago, on the Astroid issues page, "translations" : "Thanks Sonny, but why not "lib_astroid.ini" as we have "lib_joomla.ini"?" but Sonny didn't answer. :(

**Comment by infograf768** [comment]
Com_localise can't introduce specific code for any non-compliant language file.

Here is the code:
https://github.com/infograf768/j4localise/blob/0e1a86b9f4105c2e507f8f33ff693ee750630d72/administrator/components/com_localise/Model/TranslationsModel.php#L294-L344
