### ISSUE TITLE
codemirror broken for com_localise on J4

### ISSUE THREAD

**Issue by infograf768** [infograf768/j4localise#7]
When loading source of the .ini file because we have an error in the file.

<img width="1117" alt="Screen Shot 2020-05-22 at 13 06 30" src="https://user-images.githubusercontent.com/869724/82759669-26af7900-9def-11ea-92bf-79c0f1930b19.png">

J3 is fine
<img width="1168" alt="Screen Shot 2020-05-22 at 13 02 40" src="https://user-images.githubusercontent.com/869724/82759648-07185080-9def-11ea-8dea-bcefd523b5eb.png">

J4 broken
<img width="1242" alt="Screen Shot 2020-05-22 at 13 05 00" src="https://user-images.githubusercontent.com/869724/82759685-362ec200-9def-11ea-95fa-bc4a93ee2e83.png">

@C-Lodder
@SharkyKZ

**Comment by C-Lodder** [comment]
any errors in the browser console?

**Comment by SharkyKZ** [comment]
>ReferenceError: Joomla is not defined
>ReferenceError: CodeMirror is not defined

**Comment by SharkyKZ** [comment]
The path here is wrong:

https://github.com/infograf768/j4localise/blob/552abc73baa72a7baf4b26695b9566387bb0c58b/administrator/components/com_localise/Field/iniField.php#L55

If relative flag is used `media` and `js` folders should be omitted.

**Comment by infograf768** [comment]
First, thank you both for taking the time to reply.

I corrected the path and the js file is now loaded
<img width="1020" alt="Screen Shot 2020-05-25 at 07 51 19" src="https://user-images.githubusercontent.com/869724/82782486-bc352200-9e5c-11ea-8a73-a01f0bf60be9.png">

same result.
Indeed I still have
```
ReferenceError: Joomla is not defined
ReferenceError: CodeMirror is not defined

```
If I take off the `Joomla.submitbutton` script which does not —apparently— change anything here (as well as in the edit.php), I do not have the `ReferenceError: Joomla` is not defined. 
I remark though that `Joomla.submitbutton` is no more used in J4 as it was in J3, but in separate js overrides to core.js and that is a bit out of my abilities...

I still get in the raw view `CodeMirror is not defined`

It comes from the iniField.php file js part
`var editor = CodeMirror.fromTextArea(document.getElementById("jform_source"), {"mode":"text\/parseini","tabMode":"default","smartIndent":true,"lineNumbers":true,"foldGutter":true,"lineWrapping":true,"autoCloseBrackets":true,"showTrailingSpace":true,"styleActiveLine":true,"gutters":["CodeMirror-linenumbers","CodeMirror-foldgutter","breakpoints"]});
`
https://github.com/infograf768/j4localise/blob/master/administrator/components/com_localise/Field/iniField.php#L80

No idea how to solve that.

**Comment by infograf768** [comment]
@C-Lodder 
@SharkyKZ 
ping
😄

**Comment by C-Lodder** [comment]
https://github.com/infograf768/j4localise/blob/master/administrator/components/com_localise/Field/iniField.php#L79-L100

Try replacing with:

```
$html[] = '(function(Joomla, Codemirror) {';
$html[] = '		var editor = CodeMirror.fromTextArea(document.getElementById("' . $this->id . '"), ' . json_encode($options) . ');';
$html[] = '		editor.setOption("extraKeys", {';
$html[] = '			"Ctrl-Q": function(cm) {';
$html[] = '				cm.setOption("fullScreen", !cm.getOption("fullScreen"));';
$html[] = '			},';
$html[] = '			"Esc": function(cm) {';
$html[] = '				if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);';
$html[] = '			}';
$html[] = '		});';
$html[] = '		editor.on("gutterClick", function(cm, n) {';
$html[] = '			var info = cm.lineInfo(n)';
$html[] = '			cm.setGutterMarker(n, "breakpoints", info.gutterMarkers ? null : makeMarker())';
$html[] = '		})';
$html[] = '		function makeMarker() {';
$html[] = '			var marker = document.createElement("div")';
$html[] = '			marker.style.color = "#822"';
$html[] = '			marker.innerHTML = "●"';
$html[] = '			return marker';
$html[] = '		}';
$html[] = '		Joomla.editors.instances[\'' . $this->id . '\'] = editor;';
$html[] = '})(Joomla, Codemirror)';
```

**Comment by infograf768** [comment]
@C-Lodder Tested
I have a 
`ReferenceError: Joomla is not defined`
corresponding to the last line
`$html[] = '})(Joomla, Codemirror)';`

It may help you to test better by installing the present pack
[com_localise-5.0.0-dev.zip](https://github.com/infograf768/j4localise/files/4687247/com_localise-5.0.0-dev.zip)

**Comment by C-Lodder** [comment]
Ok, I've given it a test.
The problem is that you're adding inline scripts using `<script>` tags, as opposed to using `Factory::getDocument()->addScriptDeclaration('...');` or a separate file.

I've managed to fix all this and the Codemirror editor shows up. When I try to view the source of an INI file, it's empty. Is this expected?

**Comment by infograf768** [comment]
`I've managed to fix all this and the Codemirror editor shows up. When I try to view the source of an INI file, it's empty. Is this expected?`

As you can see in the screenshots above it is not expected.
let me see what I get using 
`Factory::getDocument()->addScriptDeclaration(`

**Comment by infograf768** [comment]
can you share the file you modified to use adscriptDeclaration?

**Comment by C-Lodder** [comment]
[com_localise.zip](https://github.com/infograf768/j4localise/files/4687516/com_localise.zip)
Here are the files I've updated.

I was getting an empty textarea even before the changes.

Extract to `administrator/components/com_localise`

**Comment by infograf768** [comment]
I just used your iniField.php and Issue IS SOLVED!
<img width="1416" alt="Screen Shot 2020-05-27 at 10 40 08" src="https://user-images.githubusercontent.com/869724/82997298-7c11a300-a006-11ea-9aad-965b15a84023.png">

Will do the rest as indeed the Joomla.submitbutton were broken

Thanks a lot!

**Comment by C-Lodder** [comment]
No worries, glad I could help :)

**Comment by infograf768** [comment]
Closing as solved.
